### ISSUE TITLE
Kanban board issue 

### ISSUE THREAD

**Issue by SaeqaSultani** [SaeqaSultani/Recipe-app#6]
We are two people that work on the Recipe app project. 
@SaeqaSultani 
@LIBERCOSOFT 
[The link of the project] (https://github.com/users/SaeqaSultani/projects/1)

**Comment by m05e5** [comment]
Hi @SaeqaSultani 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with the link to your repository instead of the link to your kanban board. Kindly change the link and make sure your kanban board follows microverse requirements.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @Team
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️Good issue description



## Required Changes ♻️

- [ ] kindly create cards for the following:
- Make sure there are no N+1 queries happening.
- Create a navigation menu that allows users to open all of the pages you created.

- [ ] You are also missing some cards on your board for the technical setup: [Technical setup](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements);

```
Set up the repository on GitHub and use Gitflow
Set up RSpec and Capybara testing libraries
```
-  please add it 🤗 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Omar-Muhamad** [comment]
# Approved ✔
### Hi @,

Great job, Your project is complete!  There is nothing else to say other than... it's time to close this issue and start working on the project :shipit: 

GOOD LUCK 🤞 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
